"use client";

import * as React from "react";
import {
  FileCheck2,
  Loader2,
  X,
  ShieldCheck,
  Download,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { StatusBadge } from "@/components/ui/status-badge";
import type { Decision } from "@/types";
import { formatDateTime } from "@/lib/utils";

interface Props {
  decisions: Pick<
    Decision,
    "id" | "aiSystem" | "policyRule" | "outcome" | "riskLevel" | "timestamp" | "evidenceHash"
  >[];
}

type Phase = "select" | "generating" | "done";

const STEPS = [
  "Collecting decision history",
  "Compiling approval & policy checks",
  "Aggregating audit events",
  "Computing evidence hash chain",
  "Sealing & packaging",
];

export function EvidenceGenerator({ decisions }: Props) {
  const [open, setOpen] = React.useState(false);
  const [phase, setPhase] = React.useState<Phase>("select");
  const [selected, setSelected] = React.useState<Set<string>>(new Set());
  const [step, setStep] = React.useState(0);
  const [hash, setHash] = React.useState("");

  function reset() {
    setPhase("select");
    setSelected(new Set());
    setStep(0);
    setHash("");
  }

  function toggle(id: string) {
    setSelected((prev) => {
      const next = new Set(prev);
      next.has(id) ? next.delete(id) : next.add(id);
      return next;
    });
  }

  function generate() {
    setPhase("generating");
    setStep(0);
    let i = 0;
    const timer = setInterval(() => {
      i += 1;
      setStep(i);
      if (i >= STEPS.length) {
        clearInterval(timer);
        const h =
          "0x" +
          Array.from({ length: 40 }, (_, k) =>
            ((selected.size * 7 + k * 13 + STEPS.length) % 16).toString(16),
          ).join("");
        setHash(h);
        setPhase("done");
      }
    }, 480);
  }

  function downloadJson() {
    const chosen = decisions.filter((d) => selected.has(d.id));
    const pack = {
      evidencePackId: `EVP-DRAFT-${selected.size}`,
      generatedAt: new Date().toISOString(),
      responsibleUser: "Jermaine Merritt",
      organization: "Meridian Financial Group",
      evidenceHash: hash,
      decisions: chosen,
      attestation:
        "Generated by CodexDominion Command Console — tamper-evident, hash-chained governance evidence.",
    };
    const blob = new Blob([JSON.stringify(pack, null, 2)], {
      type: "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `evidence-pack-${selected.size}-decisions.json`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <>
      <Button size="sm" onClick={() => setOpen(true)}>
        <FileCheck2 className="h-4 w-4" /> Generate Evidence Pack
      </Button>

      {open && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => {
              setOpen(false);
              reset();
            }}
          />
          <div className="relative z-10 w-full max-w-2xl overflow-hidden rounded-lg border bg-card shadow-xl">
            <div className="flex items-center justify-between border-b px-5 py-3.5">
              <div className="flex items-center gap-2">
                <FileCheck2 className="h-4 w-4 text-primary" />
                <h2 className="text-sm font-semibold">Generate Evidence Pack</h2>
              </div>
              <button
                onClick={() => {
                  setOpen(false);
                  reset();
                }}
                className="rounded-md p-1 text-muted-foreground hover:bg-accent"
              >
                <X className="h-4 w-4" />
              </button>
            </div>

            <div className="max-h-[70vh] overflow-y-auto p-5">
              {phase === "select" && (
                <>
                  <p className="mb-3 text-sm text-muted-foreground">
                    Select the decisions to seal into a tamper-evident evidence
                    pack for examination or audit.
                  </p>
                  <div className="divide-y rounded-md border">
                    {decisions.map((d) => (
                      <label
                        key={d.id}
                        className="flex cursor-pointer items-center gap-3 px-4 py-2.5 hover:bg-muted/40"
                      >
                        <input
                          type="checkbox"
                          checked={selected.has(d.id)}
                          onChange={() => toggle(d.id)}
                          className="h-4 w-4 accent-[hsl(var(--primary))]"
                        />
                        <span className="flex-1 min-w-0">
                          <span className="block font-mono text-xs font-medium">
                            {d.id}
                          </span>
                          <span className="block truncate text-xs text-muted-foreground">
                            {d.aiSystem} · {d.policyRule}
                          </span>
                        </span>
                        <StatusBadge status={d.outcome} />
                      </label>
                    ))}
                  </div>
                </>
              )}

              {phase === "generating" && (
                <div className="py-4">
                  <Progress value={(step / STEPS.length) * 100} />
                  <ul className="mt-5 space-y-2.5">
                    {STEPS.map((s, i) => (
                      <li
                        key={s}
                        className="flex items-center gap-2.5 text-sm"
                      >
                        {i < step ? (
                          <ShieldCheck className="h-4 w-4 text-success" />
                        ) : i === step ? (
                          <Loader2 className="h-4 w-4 animate-spin text-primary" />
                        ) : (
                          <span className="h-4 w-4 rounded-full border" />
                        )}
                        <span
                          className={
                            i <= step ? "" : "text-muted-foreground"
                          }
                        >
                          {s}
                        </span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {phase === "done" && (
                <div className="py-2 text-center">
                  <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-success/12">
                    <ShieldCheck className="h-6 w-6 text-success" />
                  </div>
                  <p className="text-sm font-semibold">Evidence pack sealed</p>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {selected.size} decision{selected.size === 1 ? "" : "s"}{" "}
                    packaged · {formatDateTime(new Date().toISOString())}
                  </p>
                  <div className="mx-auto mt-4 max-w-md break-all rounded-md border bg-muted/40 p-3 font-mono text-xs">
                    {hash}
                  </div>
                </div>
              )}
            </div>

            <div className="flex items-center justify-between border-t px-5 py-3">
              <span className="text-xs text-muted-foreground">
                {phase === "select"
                  ? `${selected.size} selected`
                  : phase === "done"
                    ? "Ready to export"
                    : "Working…"}
              </span>
              <div className="flex gap-2">
                {phase === "select" && (
                  <Button
                    size="sm"
                    onClick={generate}
                    disabled={selected.size === 0}
                  >
                    Generate
                  </Button>
                )}
                {phase === "done" && (
                  <>
                    <Button size="sm" variant="outline" onClick={downloadJson}>
                      <Download className="h-4 w-4" /> Download JSON
                    </Button>
                    <Button
                      size="sm"
                      onClick={() => {
                        setOpen(false);
                        reset();
                      }}
                    >
                      Done
                    </Button>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
